### ISSUE TITLE
Did someone try run on multi-gpu? Got an error in the multi-gpu setting.

### ISSUE THREAD

**Issue by Rover912** [zjunlp/DocuNet#17]
Here is the log:

Let's use 2 GPUs!
Total steps: 763
Warmup steps: 45
Traceback (most recent call last):
  File "./train_balanceloss.py", line 325, in <module>
    main()
  File "./train_balanceloss.py", line 314, in main
    train(args, model, train_features, dev_features, test_features)
  File "./train_balanceloss.py", line 137, in train
    finetune(train_features, optimizer, args.num_train_epochs, num_steps, model)
  File "./train_balanceloss.py", line 62, in finetune
    outputs = model(**inputs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/opt/conda/lib/python3.8/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in replica 0 on device 0.

Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ssd3/chunxu/docunet_predict/model_balanceloss.py", line 163, in forward
    hs, ts, entity_embs, entity_as = self.get_hrt(sequence_output, attention, entity_pos, hts)
  File "/home/ssd3/chunxu/docunet_predict/model_balanceloss.py", line 67, in get_hrt
    e_emb.append(sequence_output[i, start + offset])
IndexError: index 2 is out of bounds for dimension 0 with size 2

**Comment by zxlzr** [comment]
Hi, we have not tried running on multi-GPU. We are sorry to let you know that the released code does not support multi-GPU.

**Comment by njcx-ai** [comment]
Thank you for your observation. Perhaps there is a mismatch between the code  your device. I am sorry that i am not an expert on pytorch-based multi-GPU operation, you can refer to more multi-GPU operation manuals to modify this part of the code to match your machine.
