### ISSUE TITLE
RuntimeError: selected index k out of range

### ISSUE THREAD

**Issue by HRruiH** [zjunlp/DocuNet#35]
args: Namespace(adam_epsilon=1e-06, bert_lr=3e-05, channel_type='context-based', config_name='', data_dir='./dataset/docred', dataset='docred', dev_file='dev.json',
 down_dim=256, evaluation_steps=-1, gradient_accumulation_steps=1, learning_rate=0.0005, load_path='', log_dir='./logs/docred/train_bert-lr3e-5_accum1_unet-lr5e-4_t
ype_context-based.log', max_grad_norm=1.0, max_height=42, max_seq_length=1024, model_name_or_path='bert-base-uncased', num_class=97, num_labels=3, num_train_epochs=
30, save_path='./checkpoint/docred/train_bert-lr3e-5_accum1_unet-lr5e-4_type_context-based.pt', seed=66, test_batch_size=4, test_file='test.json', tokenizer_name='', train_batch_size=4, train_file='train_annotated.json', train_from_saved_model='', transformer_type='bert', unet_in_dim=3, unet_out_dim=256, warmup_ratio=0.06)    
load preprocessed data from ./dataset/docred\train_annotated_bert_docred.pkl.
load preprocessed data from ./dataset/docred\dev_bert_docred.pkl.
load preprocessed data from ./dataset/docred\test_bert_docred.pkl.
Total steps: 22890
Warmup steps: 1373
Logits shape: torch.Size([1310, 2])
Num labels: 3
Logits shape: torch.Size([1310, 2])
Num labels: 3
Traceback (most recent call last):
  File "./train_balanceloss.py", line 326, in <module>
    main()
  File "./train_balanceloss.py", line 315, in main
    train(args, model, train_features, dev_features, test_features)
  File "./train_balanceloss.py", line 137, in train
    finetune(train_features, optimizer, args.num_train_epochs, num_steps, model)
  File "./train_balanceloss.py", line 62, in finetune
    outputs = model(**inputs)
  File "D:\program_files\Anaconda\envs\DocuNet\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\school\AI_code\DiaKG\DocuNet\model_balanceloss.py", line 201, in forward
    output = (self.loss_fnt.get_label(logits, num_labels=self.num_labels))
  File "D:\school\AI_code\DiaKG\DocuNet\losses.py", line 43, in get_label
    top_v, _ = torch.topk(logits, num_labels, dim=1)
RuntimeError: selected index k out of range
请问这个问题怎么解决呀

**Comment by njcx-ai** [comment]
您好，建议您检查 num_labels 的值是否正确，确保它不超过 logits 张量在第二个维度上的大小。

**Comment by HRruiH** [comment]
Logits shape: torch.Size([1310, 2])
Num labels: 2
Traceback (most recent call last):
  File "./train_balanceloss.py", line 326, in <module>
    main()
  File "./train_balanceloss.py", line 315, in main
    train(args, model, train_features, dev_features, test_features)
  File "./train_balanceloss.py", line 137, in train
    finetune(train_features, optimizer, args.num_train_epochs, num_steps, model)
  File "./train_balanceloss.py", line 62, in finetune
    outputs = model(**inputs)
  File "D:\program_files\Anaconda\envs\DocuNet\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\school\AI_code\DiaKG\DocuNet\model_balanceloss.py", line 205, in forward
    loss = self.loss_fnt(logits.float(), labels.float())
  File "D:\program_files\Anaconda\envs\DocuNet\lib\site-packages\torch\nn\modules\module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\school\AI_code\DiaKG\DocuNet\losses.py", line 32, in forward
    loss = multilabel_categorical_crossentropy(labels,logits)
  File "D:\school\AI_code\DiaKG\DocuNet\losses.py", line 15, in multilabel_categorical_crossentropy
    y_pred = (1 - 2 * y_true) * y_pred
RuntimeError: The size of tensor a (97) must match the size of tensor b (2) at non-singleton dimension 1
我打印出来得到的 logits 的形状为[1310, 2]，按照您说的将num_labels 设置成了2，又出现了这个问题

**Comment by njcx-ai** [comment]
您可以尝试打印出 labels 的形状和值，以确保其形状和内容与预期一致。以及仔细检查数据准备和预处理的过程，确保标签的编码方式正确。

**Comment by zxlzr** [comment]
请问您的问题解决了吗？
